# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - air

  build:
    cmds:
      - go build -o ./bin/apiserver ./cmd/api/main.goo

  fmt:
    cmds:
      - gofmt -w .
    desc: Format code

  g:
    cmds:
      - task generate
    silent: true
    desc: Generate code
  generate:
    cmds:
      - go generate ./...
    desc: Generate code

  t:
    cmds:
      - task test
    silent: true
    desc: Run tests
  test:
    cmds:
      - go test -v ./internal/core/service/...
    desc: Run tests

  tc:
    cmds:
      - task test.cov
    silent: true
    desc: Run tests with coverage
  test.cov:
    cmds:
      - go test -covermode=count -coverprofile=covprofile.out ./internal/core/service/...
