# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - air

  build:
    cmds:
      - go build -o ./bin/apiserver ./cmd/api/main.go

  g: 
    cmds:
      - task generate
    silent: true
    desc: Generate code
  generate:
    cmds:
      - go generate ./...
    desc: Generate code