# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmd: air

  run:
    desc: Run the application
    cmds:
      - air

  b:
    desc: Build the application
    cmds:
      - task build
  build:
    cmd: go build -o ./bin/apiserver ./cmd/http/main.go

  compose:
    desc: Run the application with Docker Compose
    cmds:
      - COMPOSE_BAKE=true docker compose up -d --build

  fmt:
    cmd: gofmt -w .
    desc: Format code

  g:
    cmd: task generate
    silent: true
    desc: Generate code
  generate:
    cmd: go generate ./...
    desc: Generate code

  t:
    cmd: task test
    silent: true
    desc: Run tests
  test:
    cmd: go test ./internal/core/service/... ./internal/adapter/...
    desc: Run tests

  tc:
    cmd: task test.cov
    silent: true
    desc: Run tests with coverage
  test.cov:
    cmd: go test -covermode=count -coverprofile=covprofile.out ./internal/core/service/... ./internal/adapter/...

  swag:
    desc: "Generate swagger documentation"
    cmds:
      - swag fmt ./...
      - swag init -g ./cmd/http/main.go -o ./docs --parseInternal true
